---
# GitHub Repository Settings Configuration
repository:
  # Repository Identity
  name: nvim-personal-config
  description: "My personal Neovim configuration"

  # Repository Type Configuration
  is_template: false

  # Technology Topics
  topics:
    - neovim
    - lua
    - nvim-config

  # Repository Settings
  default_branch: main
  private: false

  # Merge Strategy Configuration
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true

  # Repository Features
  has_issues: true
  has_projects: true
  has_wiki: false
  has_discussions: true

  # Security Configuration
  enable_vulnerability_alerts: true
  enable_automated_security_fixes: true

# Enhanced Label Strategy for Template Repository
labels:
  # Core Issue Types
  - name: bug
    color: "d73a4a"
    description: "Something isn't working"
  - name: enhancement
    color: "a2eeef"
    description: "New feature or request"
  - name: documentation
    color: "0075ca"
    description: "Improvements or additions to documentation"

# Enhanced Branch Protection Rules
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
        required_conversation_resolution: true

      required_status_checks:
        strict: true
        contexts: []

      enforce_admins: false
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      require_signatures: false

      restrictions:
        users: [Excoriate]
        teams: []

# Comprehensive Security and Analysis Settings
security_and_analysis:
  secret_scanning:
    status: enabled
  secret_scanning_push_protection:
    status: enabled
  dependabot_security_updates:
    status: enabled
  dependabot_alerts:
    status: enabled
  private_vulnerability_reporting:
    status: enabled